apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novagpt-ingress
  namespace: novagpt
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: novagpt-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novagpt-frontend
                port:
                  number: 80